### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by louischatriot**
Added `express-nedb-session` to the list of session stores. It uses (as it name states) NeDB for data persistence.

### CODE REVIEW

**Comment by dougwilson** [comment]
I know it's your module and all, but I'm slightly hesitant to add it, as the very tops says:

> this library is not maintained anymore, please don't submit anymore pull requests except for bugfixes

Should people still be using it? Is there some kind of replacement people should go for instead?

**Comment by louischatriot** [comment]
Right, the phrasing is not very clear. I mean that I'll not add any feature but still take bug reports. That's a warning I copy pasted on lots of projects without rephrasing it :) I could say it's feature-freezed instead if you prefer (not like there is any feature to add anyway). In any case the underlying db is an active project.

**Comment by dougwilson** [comment]
Thanks, makes sense! You don't need to change the wording on your module, I just wanted to verify :) I have merged the PR.

**Comment by louischatriot** [comment]
Got it, thanks !

**Pull request closed without merging**
