### PR TITLE
Add sessionstore to compatible session stores.

### PR DESCRIPTION
**Pull request by ismailarilik**
Sessionstore is a node.js module for multiple databases.

### CODE REVIEW

**Comment by ismailarilik** [comment]
I couldn't understand why the image is broken...

**Comment by ismailarilik** [comment]
I could understand and fix the problem now, the pull request is ready.

**Comment by dougwilson** [comment]
Hi @ismailarilik this PR can no longer be merged, even though it is fine, because you deleted the repository. If you can please open a new PR I can get it merged.

**Comment by ismailarilik** [comment]
@dougwilson , I have open a new PR with the exact changes: https://github.com/expressjs/session/pull/532

**Pull request closed without merging**
