### PR TITLE
options add 'nextopen' item

### PR DESCRIPTION
**Pull request by cnwhy**
the default value is `true`.
if `false` and `cookie.maxAge` is any, user close browser then session loss;

### CODE REVIEW

**Comment by JoeWagner** [comment]
Are you trying to accomplish session cookies?  If so you should be able to use the default of `cookie.maxAge === null`.

Also, looks like tests are failing

**Comment by dougwilson** [comment]
So there are a few issues with this PR:

1. Can you explain exactly what this option does?
2. Can you add documentation to the README?
3. Can you add tests?

**Comment by cnwhy** [comment]
Yes, the function has been completed, but did not think of a good name, tentatively named "nextopen";  
When `nextopen == false` and sessionID time has expired, the program will add a no expiration time cookies,it is used to monitor whether the user closes the browser.  
When the user closes the browser, open the browser again to access, will first clear the sessionID, let sessionID re-initialized.

**Comment by dougwilson** [comment]
Thanks for your contribution, but this is better fit as a third-party library than in core. When `maxAge` is `false`, a user is _supposed_ to loose the session when they close the browser, which is extremely useful for people who use computers in libraries or other public places.

**Pull request closed without merging**
