### PR TITLE
Add "Partitioned" option to cookies

### LINKED ISSUE #961: [Feature Request] Support of phasing out third-party cookies
Hi 
Google plan soon to activate  phasing out third-party cookies
See Third-Party Cookies doc: https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline

Doc about phasing out third-party cookies: https://developer.chrome.com/en/docs/privacy-sandbox/third-party-cookie-phase-out/#partitioned-cookies

This feature request requires the possibility to add "Partitioned" to the cookie like Secure.

### PR DESCRIPTION
**Pull request by alexop1000**
closes #961

### CODE REVIEW

**Comment by cattermo** [comment]
@dougwilson Can we please merge and release this 🙏

**Comment by kaulshashank** [comment]
+1

**Comment by sergioRozenszajn** [comment]
Hi,
While discussing this flow we have been requested that the partition property addition would be agent dependent. This requirement comes because some old browsers/browser versions might break if an un-expected cookie property is provided.
We have tried to modify the JSession cookie dynamically, after it was generated, with no success. Express-session will then generate another cookie.
Would you consider to support a more dynamic behavior? --> for example to provide a callback function to modify JSessionID cookie properties on cookie creation.

**Comment by kaulshashank** [comment]
> Would you consider to support a more dynamic behavior? --> for example to provide a callback function to modify JSessionID cookie properties on cookie creation.

Can we also get an explicit way to set this particular cookie like it is done in this PR? Not everyone may want to do a UA check.

**Review by dougwilson — APPROVED** [review]

**Pull request merged**
