### PR TITLE
Api sessions

### PR DESCRIPTION
**Pull request by wesleytodd**
So this was my exploratory work before I knew about #164.  The idea here was basically continuing with the opinionated nature of this module, but adding support for an `Authorization` header for use with a bearer token.  Now that I see what @stalniy was doing in his PR I can see that maybe people would want a bit more flexibility.

Also worth mentioning that I don't think what is in the PR is a fully fledged option.  To be merged in this idea would need a ton of refactoring.  Also the other session backend modules would need to update, which would be a pain :)

Lastly, not sure why this particular branch is showing a commit from you, but if I were to actually make a PR that was complete I would clean it up a bunch and write tests.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Should have mentioned where the conversation for this started: #161

**Comment by wesleytodd** [comment]
Note: as I said in #161, I know this PR needs clean up before it could be merged, but I wanted to make sure the general direction was good before spending the time.

**Comment by wesleytodd** [comment]
@dougwilson are you planning on still being involved in these other projects?  If so can we start the discussion around this feature again?  If not can you point me to who can?

**Comment by cojack** [comment]
:+1: 
@dougwilson bump

**Comment by cojack** [comment]
@wesleytodd could you update your pr to resolve conflicts? Maybe @dougwilson will pull this at last.

**Comment by wesleytodd** [comment]
I can probably do that this weekend.  I do think this is a good feature to add, and have been using my fork in a few projects with no issues.

**Comment by wesleytodd** [comment]
It has been quite a while since this was opened, and I just realized I was not watching this repo.  So I do not actually know if this PR is still valid or needed anymore.  Can someone let me know if I just missed the boat on the feature?  Of if I should update this and work on it again?

**Comment by cojack** [comment]
@dougwilson could you help here?

**Comment by wesleytodd** [comment]
I am willing to put more work into this, get it updated and ready, if anyone could respond with feedback, or I can close this.  Most of this change was just breaking out the cookie handling into an abstraction so it can load the session from a header token instead.  Are there any problems with that approach?  Or suggested better ways?

**Comment by OtterCode** [comment]
@wesleytodd Let's do this. How can I help?

**Comment by wesleytodd** [comment]
I am not added on this repo, so cannot move this forward without @dougwilson or one of the other contributors adding me.  As I said in the last post, I am willing to get it updated and working again if I am assured that it will be merged.  I could update and publish my fork, but as an active express contributor I feel that that is not the way I would prefer to move forward.  I would rather push this code here.

**Comment by dougwilson** [comment]
My feedback is really the same from oh-so-long ago: I don't think this functionality belongs in this repo at all. Rather the storage of session should be extracted completely. This repo is basically just the "cookie driver".

**Comment by wesleytodd** [comment]
Ok.  I am fine with that.  Would you be open to me creating a new package in [pillarjs](https://github.com/pillarjs) which is a generic and api compatible session package with pluggable functionality like this PR provides?  Or would you rather me just move this idea out to a standalone package outside the express core ecosystem?

**Comment by OtterCode** [comment]
@wesleytodd I would certainly be grateful, and again, willing to assist and test.

**Comment by dougwilson** [comment]
Yea, a module in pillarjs would be ideal. The name "session" for the module is what we want it to be. Ideally it would be compatible with the existing express-session stores and be able to be plugged directly in this module ideally without a major version bump. We may even want to get together some time and talk about the ideas, becaude I would love to see this come to a reality.

**Comment by wesleytodd** [comment]
Maybe we could do a ctc meeting?  It has been a long time :)

**Comment by OtterCode** [comment]
@dougwilson What? I'm a little confused by what you're saying. I specifically do not want to store user information in the token, I just want to be able to recover the session ID from the Auth header instead of a cookie. It should replace this module, not plug into it.

**Comment by wesleytodd** [comment]
@OtterCode Doug is saying that he also wants that module.  But that we should create a new package in the other core express managed github org where this kind of module belongs.  And that it would provide the functionality you are looking for, just from a separate package.

**Pull request closed without merging**
