### PR TITLE
Added mssql-session-store to Compatible Session Stores.

### PR DESCRIPTION
**Pull request by jwathen**

### CODE REVIEW

**Comment by gabeio** [comment]
I would like to see the store be a little more mature before we add it to the readme. As it only has 11 commits to it.

**Comment by dougwilson** [comment]
I agree with @gabeio in that this module is very new (it only came into existence a few hours ago, even), so it's hard to judge the quality, but I don't think we can really shut people out of the list unless there is an actual independently-verifiable metric to inclusion, otherwise it's really just a subjective list.

Instead, I would ask: how does this store compare to https://www.npmjs.com/package/connect-mssql ?

Otherwise I'm going to merge this PR unless anyone has a technical objection :)

**Comment by gabeio** [comment]
I see what you mean there is no real way to *test* maturity/quality...

**Comment by jwathen** [comment]
I think it's very similar to connect-mssql which I hadn't found.  I'll collaborate with the author of that package to add some of the functionality that I'd like for the store; I'd rather not split the effort.  I do, however think that it's not a bad idea to get *some* SQL Server store listed so that others don't make the same mistake I did and assume that there's no compatible store.

**Comment by gabeio** [comment]
I wasn't stating that we didn't want mysql in there just no one who knew about that SQL Store asked to add it here it's a community effort :smile:.

**Comment by dougwilson** [comment]
We can simply add both.

**Pull request closed without merging**
