### PR TITLE
Fixed doc about custom store.

### PR DESCRIPTION
**Pull request by nleclerc**
I changed the readme section about custom store implementations because it was incomplete and misleading.
Just added the minimum correct information to get going.

### CODE REVIEW

**Comment by dougwilson** [comment]
There is no reason you need to extend the `Store` class; that only makes it easier. It's absolutely not a _must_ like this doc change says.

**Comment by nleclerc** [comment]
I changed it because at first i did create an EventEmitter and if it's
certainly necessary it's clearly not enough.
The doc probably needs to be a bit more substantial then.

**Comment by nleclerc** [comment]
And going that way, there's no obligation to extend EventEmitter either,
just conform to its signature.

**Comment by dougwilson** [comment]
> And going that way, there's no obligation to extend EventEmitter either, just conform to its signature.

We put that there because we reserve the right to start using any EE method on your store, and even static methods like `EventEmitter.listenerCount` on your store.

> The doc probably needs to be a bit more substantial then.

I 100% agree the docs for this need to be _much_ better. Currently there are so many issues coming up here, it's hard to keep up with those and find the time to provide really good docs for creating new stores. A PR with a guide to creating a store (even if the guide itself it in a separate Markdown file), is most welcome.

**Pull request closed without merging**
