### PR TITLE
Pass options to cookie.parse to avoid defaults

### PR DESCRIPTION
**Pull request by caub**
To improve perf most likely

https://github.com/jshttp/cookie/blob/master/index.js#L55-L57

### CODE REVIEW

**Comment by dougwilson** [comment]
Can you show what the perf gain is? This is harder to maintain, so I would like to be sure the gain is worth it.

**Comment by dougwilson** [comment]
Also the change breaks the jsdocs for the function.

**Comment by caub** [comment]
```js
var cookie = require('cookie');

var cookieDefaultOptions = {decode: decodeURIComponent, encode: encodeURIComponent};

// console.time(1);console.timeEnd(1);
function test1(){
	console.time(1);
	for (var i=0; i<1e4; i++) {
		cookie.parse('foo=%1;bar=bar;HttpOnly;Secure');
		cookie.parse('foo=%1;bar=bar;foo=boo');
		cookie.parse('foo=%1;bar=bar');
		cookie.parse('foo="bar=123456789&name=Magic+Mouse"');
	}
	console.timeEnd(1);
}
function test2(){
	console.time(2);
	for (var i=0; i<1e4; i++) {
		cookie.parse('foo=%1;bar=bar;HttpOnly;Secure', cookieDefaultOptions);
		cookie.parse('foo=%1;bar=bar;foo=boo', cookieDefaultOptions);
		cookie.parse('foo=%1'+i+';bar=bar', cookieDefaultOptions);
		cookie.parse('foo="bar=123456789&name=Magic+Mouse"', cookieDefaultOptions);
	}
	console.timeEnd(2);
}


setImmediate(test2)
setImmediate(test1)
setImmediate(test2)
setImmediate(test1)
setImmediate(test2)
setImmediate(test1)

/*

2: 305.208ms
1: 346.909ms
2: 304.842ms
1: 376.245ms
2: 290.874ms
1: 371.629ms
[Finished in 2.3s]
*/

```

**Comment by joewagner** [comment]
Why is there a `+i+` in line 21 for test 2, and not in test1?

When I remove that I get the following results
2: 258.397ms
1: 251.719ms
2: 233.395ms
1: 244.811ms
2: 235.622ms
1: 244.035ms

Which seems almost identical

**Comment by caub** [comment]
sorry I corrected, it's hard to see the difference now

**Comment by dougwilson** [comment]
So from the conversation above, it doesn't sound like this really does much, and the jsdoc breakage hasn't been fixed. I'm going to close this, but let me know if I misunderstood the resolution.

**Pull request closed without merging**
